USE MASTER
GO
CREATE DATABASE COMERCIO
GO
USE COMERCIO
GO
CREATE TABLE PROVEEDORES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	RAZON_SOCIAL VARCHAR(50) NOT NULL,
	CUIT BIGINT NOT NULL,
	TELEFONO BIGINT NULL,
	CELULAR BIGINT NULL,
	MAIL VARCHAR(50) NULL,
	WEB VARCHAR(50) NULL
)
GO
CREATE TABLE CLIENTES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	DNI BIGINT NOT NULL,
	FECHA_NACIMIENTO VARCHAR (50) NOT NULL,
	TELEFONO BIGINT NULL,
	CELULAR BIGINT NULL,
	MAIL VARCHAR(50) NULL
)
GO
CREATE TABLE PRODUCTOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	DESCRIPCION VARCHAR(100) NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	STOCK INT NULL,
	STOCK_MINIMO INT NULL,
	PRECIO_COMPRA DECIMAL(12,2) NULL,
	PRECIO_VENTA DECIMAL(12,2) NULL,
	PORCENTAJE DECIMAL(12,2) NULL
)
GO
CREATE TABLE DIRECCIONES_CLIENTES(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CALLE VARCHAR(100) NOT NULL,
	NUMERO INT NOT NULL,
	PISO INT NOT NULL,
	DEPARTAMENTO VARCHAR(50) NOT NULL,
	LOCALIDAD VARCHAR(50) NOT NULL,
	CODIGO_POSTAL INT NOT NULL
)
GO
CREATE TABLE DIRECCIONES_PROVEEDORES(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CALLE VARCHAR(100) NOT NULL,
	NUMERO INT NOT NULL,
	PISO INT NOT NULL,
	DEPARTAMENTO VARCHAR(50) NOT NULL,
	LOCALIDAD VARCHAR(50) NOT NULL,
	CODIGO_POSTAL INT NOT NULL
)
GO
CREATE TABLE CONTACTOS(
    ID_PROVEEDOR INT NOT NULL,
	NUMERO VARCHAR(2) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO BIGINT NULL,
	CELULAR BIGINT NULL,
	MAIL VARCHAR(50) NULL,
	FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDORES(ID)
)
GO
CREATE TABLE CORREDORES(
    ID_PROVEEDOR INT NOT NULL,
	NUMERO VARCHAR(2) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO BIGINT NULL,
	CELULAR BIGINT NULL,
	MAIL VARCHAR(50) NULL,
	FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDORES(ID)
)
GO
-- Proveedores
INSERT INTO PROVEEDORES(RAZON_SOCIAL, CUIT, TELEFONO, CELULAR, MAIL, WEB)
VALUES('Sam Ash', 2256701369, 44414599, 1177671272, 'samash@gmail.com', 'samash.com')
GO
INSERT INTO PROVEEDORES(RAZON_SOCIAL, CUIT, TELEFONO, CELULAR, MAIL, WEB)
VALUES('Daiam', 21836968369, 44414599, 1177671272, 'daiam@gmail.com', 'daiam.com')
GO
INSERT INTO PROVEEDORES(RAZON_SOCIAL, CUIT, TELEFONO, CELULAR, MAIL, WEB)
VALUES('Show Music', 24051794619, 44414599, 1177671272, 'showmusic@gmail.com', 'showmusic.com')
GO
INSERT INTO PROVEEDORES(RAZON_SOCIAL, CUIT, TELEFONO, CELULAR, MAIL, WEB)
VALUES('Guitar Center', 2317873689, 44414599, 1177671272, 'guitarcenter@gmail.com', 'guitarcenter.com')
GO
INSERT INTO PROVEEDORES(RAZON_SOCIAL, CUIT, TELEFONO, CELULAR, MAIL, WEB)
VALUES('Promúsica', 25893920179, 44414599, 1177671272, 'promusica@gmail.com', 'promusica.com')
GO
-- Contactos
INSERT INTO CONTACTOS(ID_PROVEEDOR, NUMERO, NOMBRE, APELLIDO, TELEFONO, CELULAR, MAIL) 
VALUES(1, '1A', 'Ricardo', 'Hoffer', 48253521, 1190342277, 'rhoffer@gmail.com')
GO
INSERT INTO CONTACTOS(ID_PROVEEDOR, NUMERO, NOMBRE, APELLIDO, TELEFONO, CELULAR, MAIL) 
VALUES(2, '2A', 'Ricardo', 'Hoffer', 48253521, 1190342277, 'rhoffer@gmail.com')
GO
-- Corredores
INSERT INTO CORREDORES(ID_PROVEEDOR, NUMERO, NOMBRE, APELLIDO, TELEFONO, CELULAR, MAIL) 
VALUES(1, '1A', 'Marcelo', 'Samod', 47490614, 1123487549, 'msamod@gmail.com')
GO
INSERT INTO CORREDORES(ID_PROVEEDOR, NUMERO, NOMBRE, APELLIDO, TELEFONO, CELULAR, MAIL) 
VALUES(2, '2A', 'Marcelo', 'Samod', 47490614, 1123487549, 'msamod@gmail.com')
GO
-- Clientes.
INSERT INTO CLIENTES(NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, TELEFONO, CELULAR, MAIL)
VALUES('Rómulo', 'Farías', 21656290, '22/01/81', 44414599, 1177671272, 'ronald@gmail.com')
GO
INSERT INTO CLIENTES(NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, TELEFONO, CELULAR, MAIL)
VALUES('Liliana', 'Sanchez', 27654169, '23/07/83', 43214502, 1125671200, 'ronald@gmail.com')
GO
INSERT INTO CLIENTES(NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, TELEFONO, CELULAR, MAIL)
VALUES('Sonia', 'Del Rizzo', 23654123, '23/05/76', 45714518, 1185651203, 'ronald@gmail.com')
GO
INSERT INTO CLIENTES(NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, TELEFONO, CELULAR, MAIL)
VALUES('Miguel', 'Camaño', 14654331, '28/01/62', 43214540, 1135674925, 'ronald@gmail.com')
GO
INSERT INTO CLIENTES(NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, TELEFONO, CELULAR, MAIL)
VALUES('Osvaldo', 'Salaria', 18654159, '12/01/72', 43214539, 1125671285, 'ronald@gmail.com')
GO
-- Productos.
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('M-Track 2x2 Vocal Studio', 'Interfaces Audio Midi', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('M-Track 8x4 M', 'Interfaces Audio Midi', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('Keystation 88 II', 'Controladores de Teclado', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('Code 61', 'Controladores de Teclado', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('BX5 D3', 'Monitores', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('BX Subwoofer', 'Monitores', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('Uber Mic', 'Micrófonos', 'M-Audio', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('CC28', 'Guitarras Acústica', 'Ovation', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('Nord Lead 4', 'Teclados', 'Nord', 20, 20, 20, 20, 20)
GO
INSERT INTO PRODUCTOS(DESCRIPCION, TIPO, MARCA, STOCK, STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA, PORCENTAJE)
VALUES('Nord Electro 6', 'Teclados', 'Nord', 20, 20, 20, 20, 20)
GO
-- Direcciones clientes
INSERT INTO DIRECCIONES_CLIENTES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_CLIENTES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_CLIENTES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_CLIENTES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_CLIENTES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
-- Direcciones proveedores
INSERT INTO DIRECCIONES_PROVEEDORES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_PROVEEDORES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_PROVEEDORES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_PROVEEDORES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
GO
INSERT INTO DIRECCIONES_PROVEEDORES(CALLE, NUMERO, PISO, DEPARTAMENTO, LOCALIDAD, CODIGO_POSTAL)
VALUES('Pichincha', 3342, 3, 'B', 'CABA', 1958)
